### Numpy has contigous memory as compared to lists which are like the memory block where the pointer are pointing towards them and in order keep them together they have to clutter as a result comp. memory bounces to get them

## Imports

In [4]:
import numpy as np

## Basic Revised

In [5]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [6]:
b = np.array([[6.0,5.0,4.0], [3.0,2.0,1.0]])
print(b)

[[6. 5. 4.]
 [3. 2. 1.]]


In [7]:
a.ndim
b.shape
# Get type
type(b)
a.dtype
b.dtype
# Get Size - bytes
a.itemsize
b.itemsize
# for total size
a.nbytes

12

## Accessing/Changing Specific Elements - Row,Column

In [8]:
# 2D-array of 2-Row, and 7-Col
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [9]:
a.shape

(2, 7)

In [10]:
# Get a specific element [r,c]
a[0,4]
a[0,-3]

5

In [11]:
# Get a specific whole row
a[0,:]
# Get a specific colum - all the rows (:) of that column: 2
a[:,2]

array([ 3, 10])

In [12]:
# [start:end:step] - index
# here we will give the row number, and then start_end_step - it will applied on elements
a[0, 1:6:2]

array([2, 4, 6])

In [13]:
# for changing 
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


### 3-d exmaple

In [14]:
b = np.array([[[1,2],[3,4]], [[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [15]:
# accessing, and then chainging the specific element in it
# understand it like tree
# 0 here is the set - [[1,2],[3,4]]
# 1 is the second row in that set - [3,4]
# 1 is the column in that in set - [4]
b[0,1,1]
# now changing that value there
b[0,1,1]
b[:,0,:]
b[:,1,0]

array([3, 7])

### Initializing Different Types of the Array

In [16]:
# All matrices to the zeros
# 1D
np.zeros(5)
# 2D
np.zeros((2,2))
# 3D
np.zeros((2,2,2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [17]:
# All matrix to One
ar = np.ones((2, 2))
print(ar)

[[1. 1.]
 [1. 1.]]


In [18]:
# for anyother number 
any = np.full((2,2), 69)
print(any)

[[69 69]
 [69 69]]


In [21]:
# full_like it will fill the existing array with your value
z = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(z)
z_fullike = np.full_like(a,10)
print(z_fullike)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10]]


In [22]:
# intialize array of the random numbers - you will pass in the shape
ra = np.random.rand(4,2)
print(ra)
# for filling up existing array
# ra_exist = np.random.random_sample(a.shape)

[[0.0320367  0.30754303]
 [0.41130041 0.06063529]
 [0.82502074 0.78757912]
 [0.99228313 0.27845271]]


In [24]:
# Random Integer Values
ra_int = np.random.randint(7, size=(2,3))
print(ra_int)

[[6 4 1]
 [2 0 6]]


In [26]:
  # identity matrix (3)
iden_3 = np.identity(3)
print(iden_3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [27]:
# remeber axis=1 towards horizontal, and axis=0 towards vertical one
arr = np.array([1,2,3])
rep = np.repeat(arr,3,axis=0)
print(rep)

[1 1 1 2 2 2 3 3 3]


In [28]:
output = np.ones((5,5))
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [35]:
#output_1 = np.zeros((3,3))
#z[1,1] = 9 
#print(z)

zx = np.ones((5,5))
print(zx)
zx[1,:] = 9
# if i want the zx to filled on specific row,column with 9 using np
# here i put zeros_like type to bool to create the mask shape same as zx with false filled up
mask = np.zeros_like(zx, dtype=bool)
# now updating the specific index with true
mask[1:4,1:4] = True

#Use np.fill with the mask
mask_accmomplished = np.putmask(zx,mask,9)
print(mask_accmomplished)

print(zx)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
None
[[1. 1. 1. 1. 1.]
 [9. 9. 9. 9. 9.]
 [1. 9. 9. 9. 1.]
 [1. 9. 9. 9. 1.]
 [1. 1. 1. 1. 1.]]


In [39]:
# be careful when copying
# not using .copy() will change the values in original too 
c1 = np.array([1,2,3])
c2 = c1.copy()
c2[0] = 100
print(c2)

[100   2   3]


### Mathemetics

In [40]:
m = np.array([1,2,3,4])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [43]:
m += 2
m

array([5, 6, 7, 8])

In [44]:
m *= 2
m

array([10, 12, 14, 16])

In [46]:
m / 2
m

array([10, 12, 14, 16])

In [47]:
m - 2

array([ 8, 10, 12, 14])

In [48]:
m1 = np.array([9,11,13,15])
m + m1

array([19, 23, 27, 31])

In [49]:
m ** 2

array([100, 144, 196, 256])

### Linear Algebra stuff

In [50]:
l1 = np.full((2,3), 1)
l1

array([[1, 1, 1],
       [1, 1, 1]])

In [52]:
l2 = np.full((3,2), 2)
l2  

array([[2, 2],
       [2, 2],
       [2, 2]])

In [54]:
diff_size = np.matmul(l1,l2)
diff_size

array([[6, 6],
       [6, 6]])

In [55]:
# for finding like the determinenet, you can do it as 
iden = np.identity(3)
det = np.linalg.det(iden)
det

1.0

### Find Following: determinenet, trace, singular vector decomposition, eigenvalues, matrix norm, inverse, e.t.c

### Statistics with numpy

In [56]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
# columns wise the minimum values
np.min(stats, axis=1)

array([1, 4])

In [58]:
# row wise the maximim values
np.max(stats, axis=0)

array([4, 5, 6])

In [59]:
# adding row wise (1+4, 2+5, 3+6)
np.sum(stats, axis=0)

array([5, 7, 9])

### Reorganizing the arrays - Reshaping

In [67]:
before = np.array([[1,2,3,4],[5,6,7,8]])
before
#before.shape

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [65]:
after = before.reshape((4,2))
after

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [68]:
# vertical stacking matrixes/vectors
v1 = np.array([1,2,3,4])
v2 = np.array([4,5,6,7])
np.vstack([v2,v1])

array([[4, 5, 6, 7],
       [1, 2, 3, 4]])

In [70]:
# horizontal stack
np.hstack((v2,v1))

array([4, 5, 6, 7, 1, 2, 3, 4])

### Load Data From File

In [72]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

### Advanced Indexing and Boolean Masking

In [73]:
filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [74]:
filedata[filedata > 50]

array([196.,  75., 766.,  75.,  55., 999.,  78.,  76.,  88.])

In [75]:
# u can index with list in numpy
i = np.array([1,2,3,4,5,6,7,8,9])
i[[4,8,6]]

array([5, 9, 7])

In [76]:
np.any(filedata > 50, axis = 0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [77]:
np.any(filedata > 50, axis=1)

array([ True,  True,  True])

### Quizz Time

In [78]:
quizz_matrix = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25],[26,27,27,29,30]])
quizz_matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 27, 29, 30]])

In [80]:
# Q1: get the elements 11,12,16,17
# so i can use the indexing through slicing
result = quizz_matrix
result[2:4,0:2]

array([[11, 12],
       [16, 17]])

In [81]:
# Get elements 2,8,14,20
result[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])

In [86]:
result[0:6:4,3:5]

array([[ 4,  5],
       [24, 25]])

In [88]:
result[[0,4,5], 3:5]

array([[ 4,  5],
       [24, 25],
       [29, 30]])