# Importing NumPy Libarary

In [97]:
import numpy as np
import sys as s

# Starting with Numpy

## Array: Conversion from othet Python Structures

In [98]:
listarray = np.array([[1,2,3], [5,8,5], [0,3,1]])

In [99]:
type(listarray)

numpy.ndarray

In [100]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [101]:
listarray.dtype

dtype('int32')

In [102]:
listarray.shape

(3, 3)

In [103]:
# here i made the simple list
p_list = [1,2,3,4]

In [104]:
# its type is list
type(p_list)

list

In [105]:
# now converting to numpy array
conversion_arr = np.array(p_list)

In [106]:
type(conversion_arr)

numpy.ndarray

### Intrinsic NumPy Array Creation Objects

In [107]:
# here with zero keyword i mentioned the shape of the 2D-array as (2,3)
zeros = np.zeros((2,3))

In [108]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [109]:
# I defined the range from 0 (inclusive) to 10 (exclusive)
arange = np.arange(10)

In [110]:
arange

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [111]:
# here i defined the range as (start,stop,step)
arange_1 = np.arange(2,11,2)

In [112]:
arange_1

array([ 2,  4,  6,  8, 10])

In [113]:
# linspace equally divides the numbers between a given range on set of n numbers between them
lspace = np.linspace(5,10,5)

In [114]:
lspace

array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [115]:
# empty gives you the array for the dimension you defined and fill it up with the random numbers
emp = np.empty((4,6))

In [116]:
emp

array([[1.39377403e-311, 7.60861095e-322, 0.00000000e+000,
        0.00000000e+000, 7.56571287e-307, 1.16095484e-028],
       [7.52736900e+252, 2.31463197e-152, 1.27734658e-152,
        4.19340066e+228, 4.81433628e+199, 1.81596890e-152],
       [5.35721094e+199, 1.21906099e-152, 2.43567343e-152,
        1.45913393e-152, 6.01124623e+175, 2.38954692e+180],
       [1.96032987e-152, 3.65093134e+233, 3.68790399e-110,
        6.32672800e+180, 4.74483502e+170, 1.29256215e-057]])

In [117]:
# identiy matric
iden = np.identity(3)

In [118]:
iden

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [119]:
# Now there are hell lot of functions inside this library used up few commonly used functions here

### Reshaping the NumPy Array

In [120]:
arr = np.arange(99)

In [121]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [122]:
arr = arr.reshape(3,33)


In [123]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [124]:
# for straighten up the array, i will use ravel

arr = arr.ravel()

In [125]:
arr.shape

(99,)

### Working with the axis

In [126]:
# here comes the axis 
# remember the easiet way axis 1 is towards the columns (horizontally)
# axis 0 is towards the rows (vertically)
arr_1 = ([1,2,3], [4,5,6], [7,8,9])
arr_1_converted = np.array(arr_1)

In [127]:
arr_1_converted

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [128]:
arr_1_converted.sum(axis=1)

array([ 6, 15, 24])

In [129]:
arr_1_converted.sum(axis=0)

array([12, 15, 18])

In [130]:
# for the transpose
arr_1_converted.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [131]:
# now lets get the array iterator using flat as 1D array

arr_1_converted.flat

for item in arr_1_converted.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [132]:
# it will show the dimension of the array
arr_1_converted.ndim

2

In [133]:
# for the elements count in array
arr_1_converted.size

9

In [134]:
# for the total bytes consumed
arr_1_converted.nbytes

36

In [135]:
# for the maximum element in the 2D-array, it will give its index
arr_1_converted.argmax()

8

In [136]:
# for the minimum element in the 2D-array the same will happen
arr_1_converted.argmin()

0

In [137]:
# it is giving the index number of the elements across the columns
arr_1_converted.argmax(axis=1)

array([2, 2, 2], dtype=int64)

In [138]:
# it is giving the index number of the elements acroos the rows
arr_1_converted.argmin(axis=0)

array([0, 0, 0], dtype=int64)

In [139]:
# sorting the array
arr_unsorted = np.array((9,2,3,5,0,1))

In [140]:
arr_unsorted

array([9, 2, 3, 5, 0, 1])

In [141]:
arr_unsorted.argsort()

array([4, 5, 1, 2, 3, 0], dtype=int64)

### Performing the Matrix Operations

In [142]:
arr_1_converted

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [143]:
arr_2 = np.array([[3,4,5],[7,6,1],[2,0,8]])


In [144]:
arr_2

array([[3, 4, 5],
       [7, 6, 1],
       [2, 0, 8]])

In [145]:
# now adding these two matrices
arr_1_converted + arr_2

array([[ 4,  6,  8],
       [11, 11,  7],
       [ 9,  8, 17]])

In [146]:
arr_1_converted  * arr_2

array([[ 3,  8, 15],
       [28, 30,  6],
       [14,  0, 72]])

In [147]:
np.sqrt(arr_1_converted)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [148]:
arr_1_converted.sum()

45

In [149]:
# now it will extract the maximum element out of the matrix, not the index
arr_1_converted.max()

9

In [150]:
arr_1_converted.mean()

5.0

In [151]:
arr_2

array([[3, 4, 5],
       [7, 6, 1],
       [2, 0, 8]])

In [152]:
# here the first array are the row's (1,1,2), second array are the column's (0,1,2) - so combining arr1,2 we get (1,0), (1,1), (2,2)
np.where(arr_2>5)

(array([1, 1, 2], dtype=int64), array([0, 1, 2], dtype=int64))

### Difference in size of Simple Array, and Numpy Array

In [153]:
arr_for_size = [1,3,4,5]

In [155]:
s.getsizeof(1) * len(arr_for_size)

112

In [156]:
arr_2.itemsize * arr_2.size

36

In [157]:
arr_2

array([[3, 4, 5],
       [7, 6, 1],
       [2, 0, 8]])